#!/usr/bin/env bash
# =============================================================================
# setup_udev_devices.sh
# Create stable udev symlinks for Boomy's USB serial devices.
# Run ONCE on the Pi host (not inside Docker).
#
# Usage:
#   ssh pi@<robot-ip> 'bash -s' < scripts/setup_udev_devices.sh
#
# After running:
#   /dev/ttyROSMASTER → Rosmaster sensor board (IMU, battery, gyro)
#   /dev/ttyVOICE    → AI voice/audio hat (TTS/STT)
# =============================================================================
set -euo pipefail

echo "=== Boomy USB Device Setup ==="
echo ""

# ── Discover connected USB serial devices ───────────────────────────────────

echo "--- Connected USB serial devices ---"
for dev in /dev/ttyUSB* /dev/ttyACM* 2>/dev/null; do
    [ -e "$dev" ] || continue
    info=$(udevadm info -a -n "$dev" 2>/dev/null | grep -E "ATTRS\{idVendor\}|ATTRS\{idProduct\}|ATTRS\{manufacturer\}|ATTRS\{product\}" | head -4)
    echo "  $dev:"
    echo "$info" | sed 's/^/    /'
    echo ""
done

# ── Known USB IDs ────────────────────────────────────────────────────────────
# Yahboom ROSMASTER expansion board serial chip: CH340 (1a86:7522 or 1a86:7523)
# Yahboom AI voice module: may also use CH340 or CP2102 (10c4:ea60)
# If both use CH340, we need product string or serial number to distinguish them.

ROSMASTER_VENDOR="1a86"
ROSMASTER_PRODUCT="7523"   # CH340K — most common on ROSMASTER boards; try 7522 if not found

VOICE_VENDOR="10c4"
VOICE_PRODUCT="ea60"       # CP2102 — common on Yahboom voice modules

echo "--- Creating udev rules ---"
echo "Assuming:"
echo "  ROSMASTER: VID=${ROSMASTER_VENDOR} PID=${ROSMASTER_PRODUCT} (CH340)"
echo "  VOICE HAT: VID=${VOICE_VENDOR} PID=${VOICE_PRODUCT} (CP2102)"
echo ""
echo "If both devices use CH340 (same VID:PID), we use ATTRS{serial} to distinguish."
echo "Run 'udevadm info -a -n /dev/ttyUSBx' with each device plugged in separately"
echo "to get the serial number, then edit the rules below."
echo ""

cat > /etc/udev/rules.d/99-boomy.rules << 'RULES'
# Boomy USB device stable naming
# Generated by setup_udev_devices.sh

# Yahboom ROSMASTER expansion board (CH340K)
# Provides: IMU, battery, gyro via serial protocol
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", \
    SYMLINK+="ttyROSMASTER", MODE="0666", GROUP="dialout", \
    TAG+="systemd"

# Also cover 7522 variant
SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7522", \
    SYMLINK+="ttyROSMASTER", MODE="0666", GROUP="dialout", \
    TAG+="systemd"

# Yahboom AI Voice Module (CP2102)
# Provides: TTS/STT via serial protocol
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", \
    SYMLINK+="ttyVOICE", MODE="0666", GROUP="dialout", \
    TAG+="systemd"

# Camera (if using specific USB camera)
SUBSYSTEM=="video4linux", ATTRS{idVendor}=="1bcf", SYMLINK+="video_boomy"

# I2C bus — allow dialout group access
SUBSYSTEM=="i2c-dev", MODE="0666", GROUP="i2c"

# Audio devices — allow audio group
SUBSYSTEM=="sound", GROUP="audio", MODE="0666"
RULES

echo "Rules written to /etc/udev/rules.d/99-boomy.rules"
echo ""

# ── Reload udev ──────────────────────────────────────────────────────────────
echo "--- Reloading udev ---"
udevadm control --reload-rules
udevadm trigger --subsystem-match=tty
sleep 1

# ── Verify ───────────────────────────────────────────────────────────────────
echo "--- Verification ---"
echo -n "ttyROSMASTER: "
if [ -L /dev/ttyROSMASTER ]; then
    echo "✓ $(ls -la /dev/ttyROSMASTER)"
else
    echo "NOT FOUND — check VID/PID. Run: udevadm info -a -n /dev/ttyUSB0 | grep idVendor"
fi

echo -n "ttyVOICE:     "
if [ -L /dev/ttyVOICE ]; then
    echo "✓ $(ls -la /dev/ttyVOICE)"
else
    echo "NOT FOUND — voice hat may use different VID/PID or is not plugged in"
fi

echo ""
echo "=== Next steps ==="
echo "1. If symlinks not created: identify correct VID/PID with:"
echo "   udevadm info -a -n /dev/ttyUSB0 | grep -E 'idVendor|idProduct'"
echo "   Edit /etc/udev/rules.d/99-boomy.rules and run: sudo udevadm trigger"
echo ""
echo "2. Update Docker run command to include:"
echo "   --device /dev/ttyROSMASTER:/dev/ttyROSMASTER"
echo "   --device /dev/ttyVOICE:/dev/ttyVOICE"
echo "   --device /dev/i2c-1:/dev/i2c-1"
echo "   --device /dev/video0:/dev/video0"
echo "   --device /dev/snd:/dev/snd"
echo "   --group-add dialout --group-add audio --group-add i2c"
echo ""
echo "3. Deploy patched driver to container:"
echo "   docker cp Mcnamu_driver_patched.py yahboom_ros2:/root/yahboomcar_ws/install/yahboomcar_bringup/lib/python3.10/site-packages/yahboomcar_bringup/Mcnamu_driver.py"
echo "   docker restart yahboom_ros2"
echo ""
echo "4. Install luma.oled on Pi host:"
echo "   pip3 install luma.oled luma.core pillow"
echo ""
echo "5. Run diagnose_sensors.sh to verify all sensors"
